name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push image
        run: |
          IMAGE=wisecow
          TAG=${{ github.run_number }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE:$TAG .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE:latest


      - name: Update K8s manifest with new image
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.run_number }}|g" kubernetes/wisecow-deployment.yaml


      - name: Deploy to Minikube
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          kubectl apply -f kubernetes/
